interfacerproject/interfacer-gui

- components/AssetsTable.tsx
- components/NewProjectButton.tsx
- pages/assets.tsx
- insert correct images
- add poll interval that works with pagination
> add poll interval in assets page

- components/KeyringGeneration.tsx
- components/SignInLayout.tsx
- components/VerifySeed.tsx
- cypress/e2e/auth.cy.ts
- pages/asset/[id].tsx
- pages/sign_in.tsx
- pages/sign_up.tsx
- public/locales/de/signInProps.json
- public/locales/de/signUpProps.json
- public/locales/en/signInProps.json
- public/locales/en/signUpProps.json
- public/locales/fr/signInProps.json
- public/locales/fr/signUpProps.json
- public/locales/it/signInProps.json
- public/locales/it/signUpProps.json
- translate authentication questions
- remove two step authentication
> sign_in_fixies

- cypress/component/TagSelector.cy.tsx
This should close #83 
I would like to know if this test is accurate enough – or if I should check for more things.
Also, I think the UI/UX of the field should be reviewed:
- if I delete the tag, the text inside the textarea should be deleted (not happening now)
- having both the typed text in the textarea and the same text in the badge feels like a needless duplication
- the X button should be after the word, not before
In my opinion, it should work like this https://codesandbox.io/s/react-tag-input-component-rgf97
(the tags can also stay outside the textarea)
> Created TagSelector test

- components/AssetsTable.tsx
A small bug in defining `assets` const.
At some point, there's this line:
```js
edge.node.primaryIntents[0].resourceInventoriedAs
```
but, sometimes `edge.node.primaryIntents[0]` does not exist.
So, the suggested fix is to add `?`:
```js
edge.node.primaryIntents[0]?.resourceInventoriedAs
```
---
This closes #99
> Assets table

- components/AssetsTable.tsx
- components/AssetsTableRow.tsx
This closes #101 
Created `AssetsTableRow` component in order to tidy up stuff and easily add a key for iteration.
> AssetsTable fix

- components/AddContributors.tsx
- components/GeoCoderInput.tsx
- components/brickroom/BrSearchableSelect.tsx
- cypress/component/AddContributors.cy.tsx
- cypress/component/GeoCoderInput.cy.tsx
- cypress/fixtures/addresses.json
- package.json
- pages/create_asset.tsx
- pnpm-lock.yaml
- public/locales/en/createProjectProps.json
- public/locales/it/createProjectProps.json
resolve: #28 
- select adress whit geocodind function
- use react-select for add contributors
- some rect-select theme customization
> add geocoding

- components/VerifySeed.tsx
- cypress/e2e/components/VerifySeed.cy.tsx
> Verify seed test #82

- components/AssetsTable.tsx
- components/AssetsTableRow.tsx
- components/Filters.tsx
- pages/asset/[id].tsx
- pages/create_asset.tsx
- pages/profile/[id].tsx
- save asset tags in primaryIntents.resourceClassifiedAs and retrive from there
- in asset detail page add link to conformsTo
- fix filter for profile page
- encapsulate filters
> retrieve tags and improved profile page

- components/ResourceTable.tsx
> fix(resources): 🐛 solved gql query formatting

- components/AssetsTable.tsx
- components/Filters.tsx
- components/ResourceTable.tsx
- cypress/component/AddContributors.cy.tsx
- cypress/e2e/components/AssetsTable.cy.tsx
> Broken gql query #138

- components/NewAssetForm.tsx
- components/brickroom/BrImageUpload.tsx
- public/locales/de/createProjectProps.json
- public/locales/en/createProjectProps.json
- public/locales/fr/createProjectProps.json
- public/locales/it/createProjectProps.json
> fix: drag and drop for file does not work

- pages/profile/[id].tsx
- pages/resource/[id].tsx
- public/locales/en/ProfileProps.json
- public/locales/en/ResourceProps.json
- public/locales/en/signInProps.json
- cleanup Lorem ipsum in en locales
- fix: 🐛 some string inside profile and resource detail
> remove latest lorem ipsum

- codegen.ts
- lib/types/index.ts
- package.json
- pages/resource/[id].tsx
- pnpm-lock.yaml
> feat(typescript): ✨ implemented types generation

- .github/workflows/test-deploy.yml
- package.json
> ci: 👷 does not allow concurrent build per PR

- components/AddContributors.tsx
- components/GeoCoderInput.tsx
- components/NewAssetForm.tsx
- components/SelectTags.tsx
- components/TagsGeoContributors.tsx
- components/brickroom/BrMdEditor.tsx
- components/brickroom/BrSearchableSelect.tsx
- pages/resource/claim/[id].tsx
- public/locales/en/createProjectProps.json
close: #193  
close: #194 
close: #195 
close: #196 
- fix: 🐛 react-select cursor at beginning of the trxt
- fix: 🐛 on start typing geocoder input will cancel selected value
- fix: 🐛 remove my own user from add contributors
- feat: ✨ add some key event in react-select (backspace, space and comma)
- fix: 🐛 add explanation for md-editor
> fix: some ux improvments

- components/NewAssetForm.tsx
> fix: block create asset if economic event fails and typify mutations

- cypress/e2e/profile.cy.ts
- pages/profile/[id].tsx
- public/locales/en/ProfileProps.json
> fix: in profile page of othe users should see strings not related to me

- components/AddStar.tsx
- cypress/component/AddStar.cy.tsx
- cypress/component/GeoCoderInput.cy.tsx
- cypress/e2e/asset_detail.cy.tsx
- lib/QueryAndMutation.ts
- pages/asset/[id].tsx
- public/locales/en/common.json
> feat: star the assets

- components/AssetsTable.tsx
- public/locales/en/lastUpdatedProps.json
> fix(assetsTable): 🐛 changed empty state

- components/EmailVerificationForm.tsx
- components/InvitationKey.tsx
- components/KeyringGeneration.tsx
- components/NewAssetForm.tsx
- components/TagsGeoContributors.tsx
- components/VerifySeed.tsx
- components/brickroom/BrFieldInfo.tsx
- components/brickroom/BrInput.tsx
- components/brickroom/BrInputBase.tsx
- components/brickroom/utils/index.ts
- pages/sign_in.tsx
> feat(brInput): ✨ refactor and add ref attribute

- components/brickroom/BrFieldError.tsx
- components/brickroom/BrFieldInfo.tsx
- components/brickroom/BrImageUpload.tsx
- components/brickroom/BrImageUploadEmptyState.tsx
- components/brickroom/BrImageUploadThumb.tsx
- lib/imageUpload.ts
- package.json
- pnpm-lock.yaml
- public/locales/en/BrImageUploadProps.json
- public/locales/en/createProjectProps.json
> refactor: ♻️ BrImageUpload and related

- contexts/AuthContext.tsx
> fix: homepage links should alwais redirect to logIn if nru

- pages/resource/claim/[id].tsx
- public/locales/en/ResourceProps.json
refactor with polaris ui components and yup validation
> fix: 🐛 claim asset did not work

- components/LoshPresentation.tsx
- lib/HandleCollect.ts
- pages/asset/[id].tsx
- public/locales/en/ResourceProps.json
> fix: 🐛 add to list for losh

- package.json
- pages/asset/[id].tsx
- pnpm-lock.yaml
> style: 🎨 style the dpp json

- components/brickroom/BrSelectSearchable.tsx
> fix: 🐛 searchble select options z-index

- pages/asset/[id].tsx
- public/locales/en/common.json
> fix: 🐛 hide propose a contribute on self owned assets

- components/ResourceDetailsCard.tsx
- added image
- added asset type
> Updated asset detail card

- components/RelationshipTree.tsx
- components/WatchButton.tsx
- cypress/e2e/asset_detail.cy.tsx
- cypress/e2e/auth.cy.ts
- cypress/e2e/sign_in.cy.ts
- pages/project/[id].tsx
- public/locales/en/common.json
> Improve test

- hooks/useSignedPost.ts
- hooks/useWallet.ts
this is needed in order to use wallet and inbox
> fix: 🐛 add zenflows-id to the header to some signed requests

- components/AddLicense.tsx
- components/LicenseDisplay.tsx
- components/SearchLicense.tsx
- components/partials/create/project/LicenseStep.tsx
- lib/licenses/licenses.json
- lib/licenses/types.ts
- lib/licenses/utils.ts
- pages/create/project/test.tsx
> feat: Project creation – License component

- components/partials/create/project/ImagesStep.tsx
- components/polaris/PFileUpload.tsx
- pages/create/project/test.tsx
closes #346 
new features:
- New `PFilesUpload` component
> feat: Project creation – Images component

- components/SearchProjects.tsx
- components/partials/create/project/ImportDesign.tsx
- components/partials/create/project/LinkDesign.tsx
- components/partials/create/project/MainStep.tsx
- cypress/e2e/asset_detail.cy.tsx
- lib/types/index.ts
- pages/create/project/test.tsx
> feat: Project creation – First details component

- hooks/useProjectCreation.ts
> feat: new functions for project creations

- hooks/useProjectCreation.ts
> fix: 🐛 prepare image Ifile in project creation

- components/ContributionMessage.tsx
- pages/notification.tsx
- public/locales/de/notificationProps.json
- public/locales/en/notificationProps.json
- public/locales/fr/notificationProps.json
- public/locales/it/notificationProps.json
> Fix: notification

- lib/QueryAndMutation.ts
- lib/types/index.ts
> fix: 🐛 design contribution was broken

- components/Topbar.tsx
- components/layout/NRULayout.tsx
> fix: 🐛 remove burger menu from nru layout

- components/ContributorsTable.tsx
- components/RelationshipTree.tsx
> Fix: contributors table and relations table

- components/partials/create/contribution/CreateContributionForm.tsx
- components/partials/create/project/CreateProjectForm.tsx
- components/partials/create/project/steps/ContributorsStep.tsx
- components/partials/create/project/steps/DeclarationsStep.tsx
- components/partials/create/project/steps/ImagesStep.tsx
- components/partials/create/project/steps/ImportDesignStep.tsx
- components/partials/create/project/steps/LicenseStep.tsx
- components/partials/create/project/steps/LinkDesignStep.tsx
- components/partials/create/project/steps/LocationStep.tsx
- components/partials/create/project/steps/MainStep.tsx
- components/partials/create/project/steps/RelationsStep.tsx
- components/partials/create_project/CreateProjectForm.tsx
> fix(CreateProject): 🐛 fixed validation trigger

- components/partials/create/project/steps/ImportDesignStep.tsx
- hooks/useAutoimportDefs.ts
> fix(ImportDesignStep): 🐛 changed url validation

- components/partials/create/project/CreateProjectForm.tsx
> feat(CreateProjectForm): ✨ added autofocus on field

- pages/profile/[id].tsx
- pages/projects.tsx
- chore: 🔧 change table for cards
- fix: 🐛 replace tables in favour of cards
> cards on projects page

- hooks/useAutoimport.ts
- lib/findMDRelativesUrl.ts
> feat: ✨ on autoimport github readme files fix relatives urls

- components/ProjectTime.tsx
- components/ProjectsCards.tsx
> fix: 🐛 projects last update showed wrong data

- components/partials/auth/Questions.tsx
- components/partials/create/project/steps/MainStep.tsx
- components/partials/sign_in/EnterEmail.tsx
- components/partials/sign_up/UserData.tsx
> fix: 🐛 Add focus on the first fields of forms

- contexts/AuthContext.tsx
- lib/QueryAndMutation.ts
- lib/types/index.ts
- pages/email/verify/[token].tsx
- pages/sign_up.tsx
- public/locales/de/common.json
- public/locales/de/signUpProps.json
- public/locales/en/common.json
- public/locales/en/signUpProps.json
- public/locales/fr/common.json
- public/locales/fr/signUpProps.json
- public/locales/it/common.json
- public/locales/it/signUpProps.json
> feat: Added verify email page

- components/ProjectCard.tsx
- components/ProjectThumb.tsx
> fix: 🐛 claimed projects cards dont have image

- components/Footer.tsx
> fix: 🐛 change about this platform link

- components/partials/profile/[id]/ProfileHeading.tsx
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/fr/common.json
- public/locales/it/common.json
Added "verified" badge in user profile page.
> feat(Profile): ✨ added email verified badge

- components/partials/sign_up/UserData.tsx
- cypress/e2e/auth.cy.ts
- lib/types/index.ts
- public/locales/de/signUpProps.json
- public/locales/en/signUpProps.json
- public/locales/fr/signUpProps.json
- public/locales/it/signUpProps.json
> feat(SignUp): ✨ added user and email verification

- components/ProjectsMaps.tsx
> feat(HomeMap): ✨ removed scroll zoom, added controls

- components/partials/profile/[id]/ProfileHeading.tsx
- components/partials/topbar/TopbarUser.tsx
> fix: 🐛 remove @ before username

- components/EmptyState.tsx
- components/ProjectsMaps.tsx
- hooks/useFilters.ts
> fix: 🐛 in search page map, losh should be not shown

- pages/project/[id]/index.tsx
- pages/resource/[id]/index.tsx
> fix: 🐛 project sidebar shrink too much on long title projects

- pages/notification.tsx
> fix: 🐛 if you are on /Notifications and press on Home, nothing happens

- components/AgentsTable.tsx
- components/AgentsTableBase.tsx
- public/locales/de/common.json
- public/locales/en/common.json
- public/locales/fr/common.json
- public/locales/it/common.json
> fix: 🐛 show empty state in search for users

- components/ContributionMessage.tsx
> fix: 🐛 /notification page did not show notifications

- README.md
Live demo from Beta to https://interfacer.dyne.org
> Update Live demo link in README.md
